### ISSUE TITLE
Where is backend ?

### ISSUE THREAD

**Issue by nitish-muddhey** [rushabhhere/vocab-fuzzy-search#4]
I was curious if you were making any DB calls even ? 
Is the whole dictionary dumped into browser's local storage on page loading ? 
Thankk you.

**Comment by rushabhhere** [comment]
No DB calls are being made. About 300KB of vocab data is loaded along with the website on the user's browser and is not stored anywhere - not even in local storage. The vocab data is reloaded everytime the website is visited, since it is not that much data. This also makes the website feel snappy and fast as backend calls would slow down performance significantly.
